# Generated by Django 4.2.13 on 2026-06-16 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('resume_id', models.CharField(db_index=True, max_length=36)),
                ('best_role', models.CharField(max_length=255)),
                ('match_percentage', models.FloatField(default=0)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('top_roles', models.JSONField(blank=True, default=list)),
                ('ai_suggestion', models.TextField(blank=True)),
                ('resume_score', models.PositiveIntegerField(default=0)),
                ('scored_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scored_at'],
                'indexes': [models.Index(fields=['user', 'scored_at'], name='scoring_sco_user_id_d5bd2f_idx'), models.Index(fields=['resume_id'], name='scoring_sco_resume__83e2cd_idx')],
            },
        ),
    ]
