# Generated by Django 4.2.13 on 2026-06-16 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('raw_text', models.TextField()),
                ('extracted_skills', models.JSONField(blank=True, default=list)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', 'uploaded_at'], name='resumes_res_user_id_85d325_idx'), models.Index(fields=['resume_id'], name='resumes_res_resume__586869_idx')],
            },
        ),
    ]
